[package]
name = "gru-misc"
version = "0.1.0"
authors = ["Jannik Fehre"]
edition = "2018"

[features]
color = []
io = []
time = ["spin_sleep"]
text = ["ab_glyph"]
math = []
rand = ["rand_raw", "rand_xoshiro", "rand_distr"]

[dependencies]
spin_sleep = { version = "1.0.0", optional = true }
ab_glyph = { version = "0.2.9", optional = true }
serde = { version = "1.0.129", default-features = false, features = ["derive", "std"], optional = true }
rand_raw = { package = "rand", version = "0.8.4", default-features = false, optional = true }
rand_xoshiro = { version = "0.6.0", optional = true }
rand_distr = { version = "0.4.1", default-features = false, features = ["std_math"], optional = true }
