[workspace]
members = ["gru-ui-derive"]

[package]
name = "gru-misc"
version = "0.1.0"
authors = ["Jannik Fehre"]
edition = "2021"

[features]
math = ["static_assertions"]
text = ["ab_glyph", "ahash"]
paint = ["text", "math"]
ui = ["gru-ui-derive", "paint", "copypasta"]
time = ["spin_sleep"]
rand = ["rand_raw", "rand_xoshiro", "rand_distr"]
color = []
serde_impl = ["serde", "ahash/serde"]

[dependencies]
static_assertions = { version = "1.1.0", optional = true }
ab_glyph = { version = "0.2.11", optional = true }
ahash = { version = "0.7.5", optional = true }
gru-ui-derive = { path = "gru-ui-derive", optional = true }
copypasta = { version = "0.7.1", optional = true }
spin_sleep = { version = "1.0.0", optional = true }
rand_raw = { package = "rand", version = "0.8.4", default-features = false, optional = true }
rand_xoshiro = { version = "0.6.0", optional = true }
rand_distr = { version = "0.4.1", default-features = false, features = ["std_math"], optional = true }
serde = { version = "1.0.129", default-features = false, features = ["derive", "std"], optional = true }
